### PR TITLE
strip debugging and symbol table from compiled binary

### PR DESCRIPTION
**Pull request by lpmi-13**
## Description

Add the `-s` and `-w` flags to the compile process inside the `Dockerfile`.

## How to test

build on `main` and the branch, and you should see something like the following

```
docker images | grep gobblr
gobblr-stripped                                 latest            0b6c72a360e5   28 seconds ago   34.1MB
gobblr-original                                 latest            6acecc4bd509   2 minutes ago    44.4MB
```

### CODE REVIEW

**Comment by lpmi-13** [comment]
Can fix this later while the child is doing bath time (which I am not responsible for this evening)

**Comment by lpmi-13** [comment]
the updates in this PR to the workflow are a bit clunky, and I can easily split it out into a separate workflow to _only_ run on PRs, if that would be the preference. Got denied pushing to GCR when running the action off a PR branch, which is very sensible, so tried to think of the simplest thing that would make that not happen again in future...ditto with creating a release.

**Comment by mrsimonemms** [comment]
Hi @lpmi-13, thanks for these. I'm happy with these going in one PR. It looks like the `build` job is currently failing as there's an erroneous empty `needs` in the `build.yaml`

**Comment by lpmi-13** [comment]
argggg...that's embarrassing...forgot I abandoned that path, and accidentally left that in. I'll sort it immediately :tipping_hand_man: :tophat:

**Comment by lpmi-13** [comment]
once this is all ready, I'm happy to rebase or whatever you'd prefer before merging (or you can obviously do it yourself if preferable).

**Comment by mrsimonemms** [comment]
Thanks for this @lpmi-13

**Comment by lpmi-13** [comment]
Just checking if there's anything left on my side for this, just give us a shout if so! 👍

**Review by mrsimonemms — APPROVED** [review]
Sorry, I completely missed/forgot about this. I've merged the initial commit, but changed the CI change.

Thank you very much for your contribution. Are there any additional things you'd like to see in this project?

**Comment by lpmi-13** [comment]
Can't immediately think of anything, but I'll definitely let you know if/when I'm thinking of something. 

Thanks again for creating this super cool project!

**Pull request merged**
